name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: devpass
          POSTGRES_DB: eurostat
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync

      - name: Run pytest (Code Tests)
        run: uv run pytest

      - name: Extract & Load Raw Data
        working-directory: src
        run: |
          uv run python fetch_wages.py
          uv run python fetch_inflation.py
          uv run python fetch_housing.py
        env:
          POSTGRES_PASSWORD: devpass
          POSTGRES_DB: eurostat

      - name: Create dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml << EOF
          eurostat_housing:
            outputs:
              dev:
                dbname: eurostat
                host: localhost
                pass: devpass
                port: 5433
                schema: public
                threads: 4
                type: postgres
                user: postgres
            target: dev
          EOF

      - name: Run dbt models (Transform)
        working-directory: eurostat_housing
        run: uv run dbt run
        env:
          POSTGRES_PASSWORD: devpass
          POSTGRES_DB: eurostat

      - name: Run dbt tests (Data Quality)
        working-directory: eurostat_housing
        run: uv run dbt test
        env:
          POSTGRES_PASSWORD: devpass
          POSTGRES_DB: eurostat